### ISSUE TITLE
Need some guidance

### ISSUE THREAD

**Issue by aakerbeere** [DPsystems/web-shield#1]
Many thanks to @DPsystems 

Not an issue, but a question :)

Raspberry Pi OS Bullseye

I was waiting for this since i'm running "Login-Shield" :)

I'm not sure how to set it up.

I successfully have running an instance of "Login-Shield" and to me "Web-Shield" seems to be an add-on.

So saving "START.web-shield.sh" to "/usr/local/bin/Login-Shield-master/", customize, rename to "S.web-shield.sh" and run as root should do it, right?. Will i miss something or maybe completely screw up my system?

Some guidance would be great.

**Comment by aakerbeere** [comment]
I found @DPsystems having [allready declared](https://github.com/DPsystems/Login-Shield/issues/4#issuecomment-830652096) "Web-Shield" to use different approach.
So i probably need to set it up completely independent.

**Comment by aakerbeere** [comment]
I will save the sricpts to a new folder and follow the instructions

**Comment by aakerbeere** [comment]
I always feel like a beginner :-(
```
$ sudo ./webshield-create-blacklist.sh
./webshield-create-blacklist.sh: 8: Syntax error: newline unexpected
```
```
$ sudo /usr/bin/bash ./webshield-create-blacklist.sh
./webshield-create-blacklist.sh: Zeile 7: Syntaxfehler beim unerwarteten Symbol »newline«
./webshield-create-blacklist.sh: Zeile 7: `<!DOCTYPE html>'
```

```
$ sudo /usr/bin/bash /usr/local/bin/Web-Shield-Master/webshield-create-blacklist.sh
/usr/local/bin/Web-Shield-Master/webshield-create-blacklist.sh: Zeile 7: Syntaxfehler beim unerwarteten Symbol »newline«
/usr/local/bin/Web-Shield-Master/webshield-create-blacklist.sh: Zeile 7: `<!DOCTYPE html>'
```

**Comment by aakerbeere** [comment]
@DPsystems 

You obviously copypasted the "Install-Shield" instructions. So some referings remained.

**Comment by DPsystems** [comment]
The simplest approach is to make a copy of:

webshield-set-iptables.sh-config

to 

webshield-set-iptables.sh

then run

START.web-shield.sh

(obviously all as sudo/su)

You want to look at the file webshield-set-iptables.sh-config because it lists the ports to block and you may want to alter that.

I'm not sure about some of the errors you're getting but I will update the scripts and hopefully they'll go away.

Any more issues, let me know.

**Comment by DPsystems** [comment]
I haven't tested this on a Raspberry Pi - would be interested to know if it runs on it without any mods, and if it does require mods, what are they so I can incorporate them into the docs.

**Comment by aakerbeere** [comment]
thx @DPsystems 

Im using custom port for ssh. Do i need to alter "webshield-set-iptables.sh-config"?
```
$ sudo /usr/local/bin/Web-Shield-Master/START.web-shield.sh
/usr/local/bin/Web-Shield-Master/START.web-shield.sh: 8: Syntax error: newline unexpected
```

**Comment by DPsystems** [comment]
I do not understand that "newline unexpcted" on your version of that script - maybe there's a typo after editing it?  I can't find any syntax error in the repo version - let me know if you can find out more info on what's causing that error?

Yes, to add your own ssh port modify this line in webshield-set-iptables.sh (after making a copy of the -config version)

SET_PORTS_NOWEB="20,21,80,110,143,443,989,990,993,994,995"

And add the ssh port number - also edit any of these ports as appropriate.

**Comment by DPsystems** [comment]
be sure to run git pull to get the latest versions

**Comment by aakerbeere** [comment]
I did not yet modify "webshield-set-iptables.sh". I actually added custom ssh-port to "SET_PORTS_NOWEB"

Running the script at root cli:
```
# /usr/local/bin/Web-Shield-Master/webshield-set-iptables.sh
/usr/local/bin/Web-Shield-Master/webshield-set-iptables.sh: line 7: syntax error near unexpected token `newline'
/usr/local/bin/Web-Shield-Master/webshield-set-iptables.sh: line 7: `<!DOCTYPE html>'
```

Maybe pay attention to the apostrophs surrounding the output after the colon. They are not of the same type, but i don't know if this is of any meaning.

As i understand, you tell me to clone the repository. I'm not at all familiar with git. I got the scripts using "wget https://github.com/DPsystems/web-shield/blob/b98702769d76140e3168cfcc21ad80ed003c3ebe/webshield-set-iptables.sh-config"

**Comment by aakerbeere** [comment]
Maybe i'm not understanding at all, what you are telling me.

As i understand "webshield-set-iptables.sh" is treated as a script by the system and therefor "bash" is loaded and tries to execute. But in my eyes "webshield-set-iptables.sh" does not contain any code or system function calls.

**Comment by aakerbeere** [comment]
Sorry @DPsystems 

I actually recognize to completely screwing up things.

I will first have to learn how to clone the repo. I tried yesterday but was not successful:
```
$ sudo gh repo clone DPsystems/web-shield
Klone nach 'web-shield' ...
ssh: connect to host github.com port <custom>: Connection timed out
fatal: Konnte nicht vom Remote-Repository lesen.

Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
und das Repository existiert.
exit status 128
```
Pleas forget all my earlier writings above.
I apologize.

**Comment by DPsystems** [comment]
No worries.  Let me know if I can be of any help.

**Comment by aakerbeere** [comment]
Thank you @DPsystems 

I followed the instructions on "[INSTALL](https://github.com/DPsystems/web-shield/blob/main/INSTALL)" and it seems to do the job :)
```
$ sudo /usr/local/bin/Web-Shield-Master/attack_stats.sh
|\     /|(  ____ \(  ___ \      (  ____ \|\     /|\__   __/(  ____ \( \      (  __  \ 
| )   ( || (    \/| (   ) )     | (    \/| )   ( |   ) (   | (    \/| (      | (  \  )
| | _ | || (__    | (__/ /_____ | (_____ | (___) |   | |   | (__    | |      | |   ) |
| |( )| ||  __)   |  __ ((_____)(_____  )|  ___  |   | |   |  __)   | |      | |   | |
| || || || (      | (  \ \            ) || (   ) |   | |   | (      | |      | |   ) |
| () () || (____/\| )___) )     /\____) || )   ( |___) (___| (____/\| (____/\| (__/  )
(_______)(_______/|/ \___/      \_______)|/     \|\_______/(_______/(_______/(______/ 
======= Attack Statistics based on current log files =======
 Using: /var/log/messages

From: Apr 3 00:00:50
To  : Apr 9 00:18:23

-- Number of blocked attacks in log files  : 24
-- Number of unique IP addresses attacking : 1
   Average # of attacks per IP             : 24
   Percentage of attacks from top 50 IPs   : 100.0%
   Percentage of attacks from top 10 IPs   : 100.0%
   Percentage of attacks from top 5 IPs    : 100.0%

      Top 40:
Attacks:  IP Address:
---------------------
     24 MAC=dc:a6:32:b3:34:e8:dc:ef:09:b2:be:23:08:00
```
Just great :)
Well done.

**Comment by DPsystems** [comment]
Excellent - let me know how it goes.   I need more people to test the system so we can make the blacklist as solid as possible.

**Comment by aakerbeere** [comment]
No issues so far.
The attacks have stopped 10 days later :)
thx again

**Comment by DPsystems** [comment]
Great to hear.  I'm continuing to update the lists - eventually I hope to re-write the code to make it even more user-friendly.  Thanks for helping!
